# Generated by Django 5.0.6 on 2024-06-30 18:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('citas', '0001_initial'),
        ('users', '0006_alter_user_groups_alter_user_password_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='citas',
            name='paciente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='citas', to='users.user'),
        ),
    ]
