# Generated by Django 5.0.6 on 2024-07-01 02:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('citas', '0002_alter_citas_paciente'),
    ]

    operations = [
        migrations.AddField(
            model_name='citas',
            name='estado',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('realizada', 'Realizada'), ('cancelada', 'Cancelada')], default='pendiente', max_length=10),
        ),
        migrations.AddField(
            model_name='citas',
            name='resultado',
            field=models.TextField(default=''),
        ),
    ]
