# Generated by Django 5.0.6 on 2024-06-12 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='phone',
            field=models.CharField(max_length=13, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(default='user'),
        ),
        migrations.AddField(
            model_name='user',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
